# ?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# ?? MP ??????
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

# MP ??
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ???????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??,???

  global-config:
    db-config:
      logic-delete-field: deleted # ????????????
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)