#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 2499669698@qq.com
    password: hhgrshmvjsztdide
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always


#配置MP框架日志级别
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

#MP配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰下划线转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句，调试用
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: top.hyzhu.springboot.task.entity
server:
  port: 8081
